import { type NextRequest, NextResponse } from "next/server"
import { connectToDatabase } from "@/lib/mongodb"

// Cache for traffic signs data
const cache = new Map()
const CACHE_TTL = 10 * 60 * 1000 // 10 minutes

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const category = searchParams.get("category") || "auto"
    const type = searchParams.get("type")
    const limit = Number.parseInt(searchParams.get("limit") || "50")

    // Create cache key
    const cacheKey = `traffic-signs-${category}-${type || "all"}-${limit}`

    // Check cache first
    const cached = cache.get(cacheKey)
    if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
      return NextResponse.json(cached.data)
    }

    const { db } = await connectToDatabase()

    // Build query filter
    const filter: any = {}

    // Filter by applicable vehicles
    if (category === "auto") {
      filter.applicableFor = { $in: ["auto", "alle voertuigen"] }
    } else if (category === "bromfiets") {
      filter.applicableFor = { $in: ["bromfiets", "scooter", "alle voertuigen"] }
    } else if (category === "motor") {
      filter.applicableFor = { $in: ["motor", "motorfiets", "alle voertuigen"] }
    }

    if (type && type !== "all") {
      filter.type = type
    }

    // Get traffic signs from database with optimized query
    const signs = await db
      .collection("traffic_signs")
      .find(filter)
      .limit(limit)
      .project({
        name: 1,
        description: 1,
        meaning: 1,
        type: 1,
        shape: 1,
        color: 1,
        applicableFor: 1,
        examples: 1,
      })
      .toArray()

    // If no signs found, return sample data
    if (signs.length === 0) {
      const sampleSigns = getSampleTrafficSigns(category, type, limit)
      const response = {
        signs: sampleSigns,
        total: sampleSigns.length,
        category,
      }

      // Cache the response
      cache.set(cacheKey, {
        data: response,
        timestamp: Date.now(),
      })

      return NextResponse.json(response)
    }

    const response = {
      signs,
      total: signs.length,
      category,
    }

    // Cache the response
    cache.set(cacheKey, {
      data: response,
      timestamp: Date.now(),
    })

    return NextResponse.json(response)
  } catch (error) {
    console.error("Error fetching traffic signs:", error)

    // Fallback to sample data on error
    const category = new URL(request.url).searchParams.get("category") || "auto"
    const type = new URL(request.url).searchParams.get("type")
    const limit = Number.parseInt(new URL(request.url).searchParams.get("limit") || "50")
    const sampleSigns = getSampleTrafficSigns(category, type, limit)

    return NextResponse.json({
      signs: sampleSigns,
      total: sampleSigns.length,
      category,
    })
  }
}

// Enhanced sample traffic signs data
function getSampleTrafficSigns(category: string, type: string | null, limit: number) {
  const allSigns = [
    // GEBODSBORDEN
    {
      _id: "1",
      name: "Verplicht rechtsaf",
      description: "Dit bord geeft aan dat je verplicht rechts af moet slaan",
      meaning: "Je moet de aangegeven richting volgen, andere richtingen zijn verboden",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "verkeersborden/1728908982-a19-let-op-rollende-stenen.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "2",
      name: "Verplicht linksaf",
      description: "Dit bord geeft aan dat je verplicht links af moet slaan",
      meaning: "Je moet de aangegeven richting volgen, andere richtingen zijn verboden",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "verkeersborden/1739200215-h3-voorrangsweg-van-1-kantpng.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "3",
      name: "Fietspad",
      description: "Verplicht fietspad voor fietsers en bromfietsers",
      meaning: "Alleen fietsers en bromfietsers mogen hier rijden",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739200259-h3-waarschuwing-rijbaanversmalling.png", // Updated path
      applicableFor: ["bromfiets", "fiets"],
    },

    // VERBODSBORDEN
    {
      _id: "4",
      name: "Gesloten voor alle verkeer",
      description: "Verbod voor alle voertuigen en voetgangers",
      meaning: "Niemand mag deze weg gebruiken, behalve bij uitzondering",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739200359-h3-verkeersborden-auto_a4-50-advies-snelheid.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "5",
      name: "Maximum snelheid 50",
      description: "Maximumsnelheid van 50 km/h",
      meaning: "Je mag niet harder rijden dan 50 km/h",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739280687-h3-verkeersborden-auto_b1-voorrangsweg.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "6",
      name: "Parkeerverbod",
      description: "Verbod om te parkeren",
      meaning: "Je mag hier niet parkeren",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739280712-h3-verkeersborden-auto_b3-voorrangskruispunt.png", // Updated path
      applicableFor: ["auto"],
    },

    // WAARSCHUWINGSBORDEN
    {
      _id: "7",
      name: "Gevaarlijke bocht naar rechts",
      description: "Waarschuwing voor een scherpe bocht naar rechts",
      meaning: "Verminder snelheid en bereid je voor op een scherpe bocht",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739280756-h3-verkeersborden-auto_b6-voorrang-verlenen.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "8",
      name: "Kinderen",
      description: "Waarschuwing voor spelende kinderen",
      meaning: "Extra voorzichtig rijden, kinderen kunnen onverwacht de weg op lopen",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739280789-h3-verkeersborden-auto_b7-stopbord.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "9",
      name: "Kruispunt",
      description: "Waarschuwing voor een kruispunt vooruit",
      meaning: "Let op kruisend verkeer en verleen voorrang waar nodig",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739280819-h3-verkeersborden-auto_bb03-splitsing-autosnelweg.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },

    // VOORRANGSBORDEN
    {
      _id: "10",
      name: "Voorrang verlenen",
      description: "Je moet voorrang verlenen aan verkeer op de kruisende weg",
      meaning: "Stop of vertraag om voorrang te verlenen aan ander verkeer",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739281161-h3-verkeersborden-auto_bb04-einde-of-smalle-vluchtstrook.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "11",
      name: "Stop",
      description: "Verplicht stoppen en voorrang verlenen",
      meaning: "Je moet volledig stoppen voordat je verder rijdt",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "achthoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739281207-h3-verkeersborden-auto_bb08-hectometerbord-snelweg.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "12",
      name: "Voorrangsweg",
      description: "Je rijdt op een voorrangsweg",
      meaning: "Je hebt voorrang op verkeer dat invoegt of kruist",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "ruit" as const,
      color: "geel-wit",
      image: "public/verkeersborden/1739281304-h3-verkeersborden-auto_bb09-hectometerbord-autoweg-variant.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },

    // INFORMATIEBORDEN
    {
      _id: "13",
      name: "Parkeerplaats",
      description: "Aanduiding van een parkeerplaats",
      meaning: "Hier mag je je voertuig parkeren",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739281319-h3-verkeersborden-auto_bb09-hectometerbord-autoweg.png", // Updated path
      applicableFor: ["auto"],
    },
    {
      _id: "14",
      name: "Benzinestation",
      description: "Aanduiding van een tankstation",
      meaning: "Hier kun je tanken",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282180-h3-verkeersborden-auto_bb11-bochtschild.png", // Updated path
      applicableFor: ["auto", "motor"],
    },
    {
      _id: "15",
      name: "Ziekenhuis",
      description: "Aanduiding richting ziekenhuis",
      meaning: "Volg deze route naar het ziekenhuis",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282227-h3-verkeersborden-auto_bb23-spoorwegovergang-over-80-meter.png", // Updated path
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "16",
      name: "Let op: Rollende Stenen",
      description: "Waarschuwing voor vallende of rollende stenen.",
      meaning: "Wees voorzichtig, er kunnen stenen op de weg liggen of vallen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282343-h3-verkeersborden-auto_bb23-spoorwegovergang-over-160-meter.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "17",
      name: "Voorrangsweg van 1 kant",
      description: "Geeft aan dat de voorrangsweg van één kant komt.",
      meaning: "Verkeer nadert van een voorrangsweg vanuit één richting; wees voorbereid op het verlenen of krijgen van voorrang.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "vierkant" as const, // This sign is usually a square or rectangle
      color: "blauw-wit",
      image: "public/verkeersborden/1739282458-h3-verkeersborden-auto_bb23-spoorwegovergang-over-240-meter.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "18",
      name: "Waarschuwing rijbaanversmalling",
      description: "Waarschuwing voor een versmalling van de rijbaan vooruit.",
      meaning: "De weg wordt smaller; pas je snelheid aan en wees voorbereid op tegemoetkomend verkeer.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282517-h3-verkeersborden-auto_bw501r-uitwijkroute-rechts-afslaan.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "19",
      name: "Advies snelheid 50",
      description: "Advies om 50 km/u te rijden.",
      meaning: "Het wordt aangeraden om niet sneller dan 50 km/u te rijden voor een veilige doorstroming van het verkeer.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739282604-h3-verkeersborden-auto_c1-verbodsborden.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "20",
      name: "Voorrangsweg (B1)",
      description: "Geeft aan dat je op een voorrangsweg rijdt.",
      meaning: "Je hebt voorrang op kruisende wegen en invoegend verkeer.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "ruit" as const,
      color: "geel-wit",
      image: "public/verkeersborden/1739282647-h3-verkeersborden-auto_c2-ob4-verboden-in-te-rijden-inclusief-afgebeelde-voertuigen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "21",
      name: "Voorrangskruispunt",
      description: "Waarschuwing voor een kruispunt waar voorrang moet worden verleend.",
      meaning: "Nader een kruispunt waar voorrangsregels van toepassing zijn; wees voorbereid op het verlenen of krijgen van voorrang.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282719-h3-verkeersborden-auto_c2-ob52-verboden-in-te-rijden-met-uitzondering.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "22",
      name: "Voorrang verlenen (B6)",
      description: "Je moet voorrang verlenen aan verkeer op de kruisende weg.",
      meaning: "Stop of vertraag om voorrang te verlenen aan ander verkeer.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282751-h3-verkeersborden-auto_c3-eenrichtingsweg.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "23",
      name: "Stopbord (B7)",
      description: "Verplicht stoppen en voorrang verlenen.",
      meaning: "Je moet volledig stoppen voordat je verder rijdt.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "achthoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282819-h3-verkeersborden-auto_c04r-eenrichtingsweg-rechts.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "24",
      name: "Splitsing Autosnelweg",
      description: "Voorwaarschuwing voor een splitsing op een autosnelweg.",
      meaning: "De snelweg splitst zich; kies tijdig de juiste rijstrook.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282864-h3-verkeersborden-auto_c05-inrijden-toegestaan.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "25",
      name: "Einde of Smalle Vluchtstrook",
      description: "Geeft het einde van een vluchtstrook aan, of een smalle vluchtstrook.",
      meaning: "Wees bewust van de beperkte ruimte op de vluchtstrook of het einde ervan.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282899-h3-verkeersborden-auto_c6-verboden-voor-autos.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "26",
      name: "Hectometerbord Snelweg",
      description: "Geeft de afstand aan in hectometers op de snelweg.",
      meaning: "Informatie over de afgelegde afstand op de snelweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "wit-groen",
      image: "public/verkeersborden/1739282976-h3-verkeersborden-auto_c7-gesloten-voor-vrachtwagens.png",
      applicableFor: ["alle voertuigen"],
    },
    {
      _id: "27",
      name: "Hectometerbord Autoweg Variant",
      description: "Geeft de afstand aan in hectometers op een autoweg (variant).",
      meaning: "Informatie over de afgelegde afstand op de autoweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "wit-blauw",
      image: "public/verkeersborden/1739283011-h3-verkeersborden-auto_c9-gesloten-verklaring-tracktor-bromfiets-fiets.png",
      applicableFor: ["alle voertuigen"],
    },
    {
      _id: "28",
      name: "Hectometerbord Autoweg",
      description: "Geeft de afstand aan in hectometers op een autoweg.",
      meaning: "Informatie over de afgelegde afstand op de autoweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "wit-blauw",
      image: "public/verkeersborden/1739283077-h3-verkeersborden-auto_c11-gesloten-voor-motorfietsen.png",
      applicableFor: ["alle voertuigen"],
    },
    {
      _id: "29",
      name: "Bochtschild",
      description: "Geeft de richting van een bocht aan en waarschuwt voor een scherpe bocht.",
      meaning: "Volg de richting van het schild; pas snelheid aan voor de bocht.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "rechthoek" as const,
      color: "zwart-wit",
      image: "public/verkeersborden/1739283178-h3-verkeersborden-auto_c12-verboden-voor-autos-en-motoren.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "30",
      name: "Spoorwegovergang over 80 meter",
      description: "Waarschuwing voor een spoorwegovergang binnen 80 meter.",
      meaning: "Wees voorbereid op een spoorwegovergang; nader deze voorzichtig.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "paal met strepen" as const,
      color: "wit-rood",
      image: "public/verkeersborden/1739283238-h3-verkeersborden-auto_c16-verboden-voor-voetgangers.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "31",
      name: "Spoorwegovergang over 160 meter",
      description: "Waarschuwing voor een spoorwegovergang binnen 160 meter.",
      meaning: "Wees voorbereid op een spoorwegovergang; nader deze voorzichtig.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "paal met strepen" as const,
      color: "wit-rood",
      image: "public/verkeersborden/1739283267-h3-verkeersborden-auto_c19-gesloten-voor-te-hoge-voertuigen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "32",
      name: "Spoorwegovergang over 240 meter",
      description: "Waarschuwing voor een spoorwegovergang binnen 240 meter.",
      meaning: "Wees voorbereid op een spoorwegovergang; nader deze voorzichtig.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "paal met strepen" as const,
      color: "wit-rood",
      image: "public/verkeersborden/1739283326-h3-verkeersborden-auto_d2-passeren-aan-rechterzijde.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "33",
      name: "Uitwijkroute Rechts Afslaan",
      description: "Geeft een alternatieve route aan die rechtsaf slaat.",
      meaning: "Volg deze route als de normale weg geblokkeerd is of als omleiding.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "geel-zwart",
      image: "public/verkeersborden/1739283453-h3-verkeersborden-auto_d4-gebod-tot-volgen-van-aangegeven-rijrichting.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "34",
      name: "Gesloten voor alle verkeer (C1)",
      description: "Verbod voor alle voertuigen en voetgangers.",
      meaning: "Niemand mag deze weg gebruiken, behalve bij uitzondering.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739283513-h3-verkeersborden-auto_d5-gebod-tot-volgen-aangegeven-rijrichting.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen", "voetganger"],
    },
    {
      _id: "35",
      name: "Verboden In Te Rijden (C2 - Ob4)",
      description: "Verboden om in te rijden, inclusief afgebeelde voertuigen.",
      meaning: "De weg is gesloten voor verkeer in deze richting.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739283657-h3-verkeersborden-auto_d104-bromfietsers-moeten-wisselen-van-rijbaan.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "vrachtwagen"],
    },
    {
      _id: "36",
      name: "Verboden In Te Rijden (C2 - Ob52)",
      description: "Verboden om in te rijden, met uitzondering van bepaalde voertuigen.",
      meaning: "De weg is gesloten voor verkeer in deze richting, tenzij anders aangegeven voor specifieke voertuigen.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739283792-h3-verkeersborden-auto_e01-parkeerverbod.png",
      applicableFor: ["auto", "bromfiets", "motor", "vrachtwagen"], // Adjust based on the actual exception
    },
    {
      _id: "37",
      name: "Eenrichtingsweg (C3)",
      description: "Geeft een eenrichtingsweg aan.",
      meaning: "Verkeer mag alleen in de aangegeven richting rijden.",
      category: "gebod",
      type: "gebod" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739283954-h3-verkeersborden-auto_e02-verboden-stil-te-staan.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "38",
      name: "Eenrichtingsweg Rechts (C04r)",
      description: "Geeft een eenrichtingsweg aan waar het verkeer rechtsaf moet slaan.",
      meaning: "Verkeer mag alleen rechtsaf slaan op deze eenrichtingsweg.",
      category: "gebod",
      type: "gebod" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739283993-h3-verkeersborden-auto_e7-parkeergelegenheid-laden-en-lossen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "39",
      name: "Inrijden Toegestaan (C05)",
      description: "Geeft aan dat inrijden is toegestaan.",
      meaning: "Je mag deze weg inrijden.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739284064-h3-verkeersborden-auto_e12-parkeer-en-reisvoorziening.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "40",
      name: "Verboden voor Auto's (C6)",
      description: "Verboden toegang voor auto's.",
      meaning: "Auto's mogen deze weg niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284094-h3-verkeersborden-auto_f05-tegenligger-heeft-voorrang.png",
      applicableFor: ["auto"],
    },
    {
      _id: "41",
      name: "Gesloten voor Vrachtwagens (C7)",
      description: "Gesloten voor vrachtwagens.",
      meaning: "Vrachtwagens mogen deze weg niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284138-h3-verkeersborden-auto_f7-keerverbod.png",
      applicableFor: ["vrachtwagen"],
    },
    {
      _id: "42",
      name: "Gesloten voor Tractor, Bromfiets, Fiets (C9)",
      description: "Gesloten voor tractoren, bromfietsen en fietsen.",
      meaning: "Deze voertuigen mogen deze weg niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284165-h3-verkeersborden-auto_f8-einde-aangegeven-verboden-door-verkeersborden.png",
      applicableFor: ["tractor", "bromfiets", "fiets"],
    },
    {
      _id: "43",
      name: "Gesloten voor Motorfietsen (C11)",
      description: "Gesloten voor motorfietsen.",
      meaning: "Motorfietsen mogen deze weg niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284210-h3-verkeersborden-auto_g1-autosnelweg.png",
      applicableFor: ["motor"],
    },
    {
      _id: "44",
      name: "Verboden voor Auto's en Motoren (C12)",
      description: "Verboden toegang voor auto's en motoren.",
      meaning: "Auto's en motoren mogen deze weg niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284828-h3-verkeersborden-auto_g5-woonerf.png",
      applicableFor: ["auto", "motor"],
    },
    {
      _id: "45",
      name: "Verboden voor Voetgangers (C16)",
      description: "Verboden toegang voor voetgangers.",
      meaning: "Voetgangers mogen deze weg niet betreden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284866-h3-verkeersborden-auto_g7-voetpad.png",
      applicableFor: ["voetganger"],
    },
    {
      _id: "46",
      name: "Gesloten voor Te Hoge Voertuigen (C19)",
      description: "Gesloten voor voertuigen hoger dan de aangegeven hoogte.",
      meaning: "Voertuigen die hoger zijn dan de maximale toegestane hoogte mogen hier niet inrijden.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739284890-h3-verkeersborden-auto_g11-fietspad.png",
      applicableFor: ["vrachtwagen", "bus", "camper", "voertuigen met hoge lading"],
    },
    {
      _id: "47",
      name: "Passeren aan Rechterzijde (D2)",
      description: "Gebod om aan de rechterzijde te passeren.",
      meaning: "Je moet dit obstakel of verkeer aan de rechterkant passeren.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739284935-h3-verkeersborden-auto_j1-slecht-wegdek.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "48",
      name: "Gebod tot Volgen van Aangegeven Rijrichting (D4)",
      description: "Gebod om de aangegeven rijrichting te volgen.",
      meaning: "Je bent verplicht de pijlrichting te volgen.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739284974-h3-verkeersborden-auto_j2-let-op-overstekend-vee.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "49",
      name: "Gebod tot Volgen Aangegeven Rijrichting (D5)",
      description: "Gebod om de aangegeven rijrichting te volgen (variant).",
      meaning: "Je bent verplicht de pijlrichting te volgen.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739285005-h3-verkeersborden-auto_j02-vooraanduiding-bocht-naar-rechts.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "50",
      name: "Bromfietsers Moeten Wisselen van Rijbaan (D104)",
      description: "Bromfietsers moeten van rijbaan wisselen.",
      meaning: "Dit bord geeft aan dat bromfietsers een andere rijbaan moeten nemen.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739285037-h3-verkeersborden-auto_j03-vooraanduiding-bocht-naar-links.png",
      applicableFor: ["bromfiets"],
    },
    {
      _id: "51",
      name: "Parkeerverbod (E01)",
      description: "Verbod om te parkeren.",
      meaning: "Je mag hier niet parkeren.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-blauw",
      image: "public/verkeersborden/1739288254-h3-verkeersborden-auto_j6-steile-helling.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "52",
      name: "Verboden Stil Te Staan (E02)",
      description: "Verboden om stil te staan.",
      meaning: "Je mag hier niet stoppen, ook niet om passagiers in of uit te laten stappen of om te laden/lossen.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-blauw",
      image: "public/verkeersborden/1739288352-h3-verkeersborden-auto_j7-gevaarlijke-daling.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "53",
      name: "Parkeergelegenheid Laden en Lossen (E7)",
      description: "Parkeergelegenheid speciaal voor laden en lossen.",
      meaning: "Deze plek is gereserveerd voor het in- en uitladen van goederen.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739288393-h3-verkeersborden-auto_j8-gevaarlijk-kruispunt.png",
      applicableFor: ["vrachtwagen", "bestelbus", "auto"],
    },
    {
      _id: "54",
      name: "Parkeer- en Reisvoorziening (E12)",
      description: "Aanduiding van een parkeer- en reisvoorziening (P+R).",
      meaning: "Hier kun je parkeren en verder reizen met openbaar vervoer.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739288426-h3-verkeersborden-auto_j10-spoorwegovergang-met-spoorbomen.png",
      applicableFor: ["auto"],
    },
    {
      _id: "55",
      name: "Tegenligger Heeft Voorrang (F05)",
      description: "Tegenliggers op smalle doorgang hebben voorrang.",
      meaning: "Verleen voorrang aan tegemoetkomend verkeer in deze smalle sectie.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "rond" as const,
      color: "blauw-rood",
      image: "public/verkeersborden/1739288463-h3-verkeersborden-auto_j11-spoorwegovergang-zonder-spoorbomen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "56",
      name: "Keerverbod (F7)",
      description: "Verbod om te keren.",
      meaning: "Je mag hier geen U-bocht maken.",
      category: "verbod",
      type: "verbod" as const,
      shape: "rond" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288499-h3-verkeersborden-auto_j12-spoorweg-overweg-met-enkel-spoor.png",
      applicableFor: ["auto", "bromfiets", "motor", "vrachtwagen"],
    },
    {
      _id: "57",
      name: "Einde Aangegeven Verboden door Verkeersborden (F8)",
      description: "Einde van alle eerder aangegeven verboden door verkeersborden.",
      meaning: "Eerder opgelegde verboden, zoals snelheidsbeperkingen of inhaalverboden, zijn hier opgeheven.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rond" as const,
      color: "grijs",
      image: "public/verkeersborden/1739288626-h3-verkeersborden-auto_j20-let-op-slipgevaar.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "58",
      name: "Autosnelweg (G1)",
      description: "Geeft het begin van een autosnelweg aan.",
      meaning: "Je betreedt een autosnelweg met specifieke regels (o.a. minimumsnelheid, inhaalregels).",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739288673-h3-verkeersborden-auto_j20-ob411-slipgevaar-met-afstandinformatie.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "59",
      name: "Woonerf (G5)",
      description: "Geeft het begin van een woonerf aan.",
      meaning: "In een woonerf gelden speciale regels: stapvoets rijden, voetgangers mogen overal lopen en spelen, parkeren alleen op aangegeven plaatsen.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739288709-h3-verkeersborden-auto_j21-let-op-kinderen.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "voetganger", "alle voertuigen"],
    },
    {
      _id: "60",
      name: "Voetpad (G7)",
      description: "Verplicht voetpad voor voetgangers.",
      meaning: "Alleen voetgangers mogen dit pad gebruiken.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739288737-h3-verkeersborden-auto_j24-let-op-voetgangers.png",
      applicableFor: ["voetganger"],
    },
    {
      _id: "61",
      name: "Fietspad (G11)",
      description: "Verplicht fietspad voor fietsers.",
      meaning: "Alleen fietsers mogen dit pad gebruiken.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rond" as const,
      color: "blauw",
      image: "public/verkeersborden/1739288761-h3-verkeersborden-auto_j27-let-op-groot-wild.png",
      applicableFor: ["fiets"],
    },
    {
      _id: "62",
      name: "Slecht Wegdek (J1)",
      description: "Waarschuwing voor een slecht wegdek.",
      meaning: "Wees voorzichtig, de weg kan ongelijk, beschadigd of glad zijn.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288801-h3-verkeersborden-auto_j29-let-op-tegenliggers.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "63",
      name: "Let op: Overstekend Vee (J2)",
      description: "Waarschuwing voor overstekend vee.",
      meaning: "Wees voorbereid op dieren op de weg; verminder snelheid.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288826-h3-verkeersborden-auto_j31-vooraanduiding-zijwind.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "64",
      name: "Vooraanduiding Bocht naar Rechts (J02)",
      description: "Voorwaarschuwing voor een bocht naar rechts.",
      meaning: "Bereid je voor op een bocht naar rechts; pas je snelheid aan.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288926-h3-verkeersborden-auto_j33-kans-op-file.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "65",
      name: "Vooraanduiding Bocht naar Links (J03)",
      description: "Voorwaarschuwing voor een bocht naar links.",
      meaning: "Bereid je voor op een bocht naar links; pas je snelheid aan.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288953-h3-verkeersborden-auto_j34-vooraanduiding-ongeval.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "66",
      name: "Steile Helling (J6)",
      description: "Waarschuwing voor een steile helling.",
      meaning: "Pas je rijgedrag aan voor een steile klim; gebruik de juiste versnelling.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739288981-h3-verkeersborden-auto_j35-let-op-slecht-zicht-bij-regen-sneeuw-mist.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "67",
      name: "Gevaarlijke Daling (J7)",
      description: "Waarschuwing voor een gevaarlijke daling.",
      meaning: "Pas je rijgedrag aan voor een steile afdaling; gebruik de juiste versnelling.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289070-h3-verkeersborden-auto_j37-let-op-drempel.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "68",
      name: "Gevaarlijk Kruispunt (J8)",
      description: "Waarschuwing voor een gevaarlijk kruispunt.",
      meaning: "Wees extra voorzichtig bij dit kruispunt; er kunnen onverwachte situaties ontstaan.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289100-h3-verkeersborden-auto_j39-let-op-uitschuifbare-paal.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "69",
      name: "Spoorwegovergang met Spoorbomen (J10)",
      description: "Waarschuwing voor een spoorwegovergang met spoorbomen.",
      meaning: "Er nadert een spoorwegovergang die beveiligd is met spoorbomen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289219-h3-verkeersborden-auto_k2-voorwegwijzer-langs-autosnelweg.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "70",
      name: "Spoorwegovergang zonder Spoorbomen (J11)",
      description: "Waarschuwing voor een spoorwegovergang zonder spoorbomen.",
      meaning: "Wees extra voorzichtig; er is geen slagboom aanwezig om het verkeer te regelen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289257-h3-verkeersborden-auto_k4-hoge-beslissingswijzer-langs-autosnelweg.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "71",
      name: "Spoorweg Overweg met Enkel Spoor (J12)",
      description: "Waarschuwing voor een spoorwegovergang met enkel spoor.",
      meaning: "Er is een spoorwegovergang met één spoorlijn; wees voorbereid op passerende treinen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289285-h3-verkeersborden-auto_k5-voorwegwijzer-langs-niet-autosnelweg.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "72",
      name: "Let op: Slipgevaar (J20)",
      description: "Waarschuwing voor slipgevaar.",
      meaning: "De weg kan glad zijn door bijvoorbeeld regen, ijzel, sneeuw of modder; pas snelheid en rijgedrag aan.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289328-h3-verkeersborden-auto_k13-wegwijzer-met-wijknummers-binnen-bebouwde-kom.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "73",
      name: "Slipgevaar met Afstandsinformatie (J20 - Ob411)",
      description: "Waarschuwing voor slipgevaar met aanvullende afstandsinformatie.",
      meaning: "De weg kan glad zijn over een bepaalde afstand; pas snelheid en rijgedrag aan.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289370-h3-verkeersborden-auto_k14-route-voor-vervoer-gevaarlijkes-stoffen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "74",
      name: "Let op: Kinderen (J21)",
      description: "Waarschuwing voor spelende kinderen of kinderen in de buurt van de weg.",
      meaning: "Wees extra voorzichtig; kinderen kunnen onverwacht de weg op komen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289450-h3-verkeersborden-auto_l2-voetgangersoversteekplaats.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "75",
      name: "Let op: Voetgangers (J24)",
      description: "Waarschuwing voor voetgangers op of langs de weg.",
      meaning: "Wees voorbereid op overstekende of lopende voetgangers.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289568-h3-verkeersborden-auto_l08-doodlopende-weg.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "76",
      name: "Let op: Groot Wild (J27)",
      description: "Waarschuwing voor overstekend groot wild.",
      meaning: "Wees extra voorzichtig, vooral in de schemering; er kunnen wilde dieren op de weg komen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289637-h3-verkeersborden-auto_l09-voorwaarschuwing-doodlopende-weg-links.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "77",
      name: "Let op: Tegenliggers (J29)",
      description: "Waarschuwing voor tegemoetkomend verkeer op een smalle weg of waar dit onverwacht is.",
      meaning: "Wees voorbereid op tegenliggers; houd rekening met de breedte van de weg.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289672-h3-verkeersborden-auto_l09-voorwaarschuwing-doodlopende-weg.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "78",
      name: "Vooraanduiding Zijwind (J31)",
      description: "Waarschuwing voor (sterke) zijwind.",
      meaning: "Wees voorzichtig, vooral op open vlaktes of bruggen; je voertuig kan door wind worden beïnvloed.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289697-h3-verkeersborden-auto_l11-aangegeven-rijstrook-heeft-breedte-beperking.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "vrachtwagen", "alle voertuigen"],
    },
    {
      _id: "79",
      name: "Kans op File (J33)",
      description: "Waarschuwing voor kans op file of langzaam rijdend verkeer.",
      meaning: "De verkeerssituatie kan vertraagd zijn; wees voorbereid op filevorming.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289726-h3-verkeersborden-auto_l14-vluchthaven.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "80",
      name: "Vooraanduiding Ongeval (J34)",
      description: "Voorwaarschuwing voor een ongeval.",
      meaning: "Wees extra voorzichtig en verminder snelheid; er is een ongeval gebeurd of in behandeling.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289751-h3-verkeersborden-auto_l20-uitwijkplaats-rechts.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "81",
      name: "Let op: Slecht Zicht (J35)",
      description: "Waarschuwing voor slecht zicht door regen, sneeuw of mist.",
      meaning: "De zichtbaarheid is beperkt; pas je snelheid aan en voer dimlicht of mistlicht.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289778-h3-verkeersborden-auto_l51-fietsstraat.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "82",
      name: "Let op: Drempel (J37)",
      description: "Waarschuwing voor een verkeersdrempel.",
      meaning: "Verminder snelheid; er is een drempel in de weg om het verkeer te vertragen.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289801-h3-verkeersborden-auto_matrixbord-einde-aangegeven-verboden-adviezen.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "83",
      name: "Let op: Uitschuifbare Paal (J39)",
      description: "Waarschuwing voor een uitschuifbare paal (pollers).",
      meaning: "Wees alert op een paal die uit de grond kan komen om verkeer te reguleren.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739289847-h3-verkeersborden-auto_matrixbord-verdrijfbord-links.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "84",
      name: "Voorwegwijzer langs Autosnelweg (K2)",
      description: "Voorwegwijzer die de te volgen richting aangeeft op een autosnelweg.",
      meaning: "Geeft de juiste rijstrook aan voor de bestemming op de autosnelweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rechthoek" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739289883-h3-verkeersborden-auto_ob11-onderbord-voor-fietsen.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "85",
      name: "Hoge Beslissingswijzer langs Autosnelweg (K4)",
      description: "Hoge beslissingswijzer die de rijstroken en bestemmingen aangeeft op een autosnelweg.",
      meaning: "Geeft de verschillende rijstroken en bijbehorende bestemmingen aan, vaak boven de weg geplaatst.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rechthoek" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739289907-h3-verkeersborden-auto_ob12-onderbord-voor-bussen.png",
      applicableFor: ["auto", "motor", "vrachtwagen"],
    },
    {
      _id: "86",
      name: "Voorwegwijzer langs Niet-Autosnelweg (K5)",
      description: "Voorwegwijzer die de te volgen richting aangeeft op een weg die geen autosnelweg is.",
      meaning: "Geeft de juiste rijstrook aan voor de bestemming op een niet-snelweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rechthoek" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739289934-h3-verkeersborden-auto_ob61-onderbord-voor-vrachtwagens-met-tijden.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "87",
      name: "Wegwijzer met Wijknummers Binnen Bebouwde Kom (K13)",
      description: "Wegwijzer die de route naar verschillende wijknummers binnen de bebouwde kom aangeeft.",
      meaning: "Helpt bij het navigeren naar specifieke wijken in stedelijke gebieden.",
      category: "informatie",
      type: "informatie" as const,
      shape: "rechthoek" as const,
      color: "wit-zwart",
      image: "public/verkeersborden/1739289973-h3-verkeersborden-auto_voorrangsborden.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "88",
      name: "Route voor Vervoer Gevaarlijke Stoffen (K14)",
      description: "Geeft de verplichte route aan voor het vervoer van gevaarlijke stoffen.",
      meaning: "Voertuigen met gevaarlijke stoffen moeten deze specifieke route volgen.",
      category: "gebod",
      type: "gebod" as const,
      shape: "rechthoek" as const,
      color: "wit-zwart",
      image: "public/verkeersborden/1739289998-h3-verkeersborden-auto_vr07-verkeersbrigadier-bij-zebrapad.png",
      applicableFor: ["vrachtwagen met gevaarlijke stoffen"],
    },
    {
      _id: "89",
      name: "Voetgangersoversteekplaats (L2)",
      description: "Aanduiding van een voetgangersoversteekplaats (zebrapad).",
      meaning: "Hier hebben voetgangers voorrang bij het oversteken.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739290024-h3-verkeersborden-auto_waarschuwingsbord.png",
      applicableFor: ["voetganger", "auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "90",
      name: "Doodlopende Weg (L08)",
      description: "Aanduiding van een doodlopende weg.",
      meaning: "De weg loopt dood; er is geen uitgang voor doorgaand verkeer.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739290045-h3-verkeersborden-auto_wiu-t201-omleidingsroute-volgen-rechtsaf.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "91",
      name: "Voorwaarschuwing Doodlopende Weg Links (L09)",
      description: "Voorwaarschuwing voor een doodlopende weg naar links.",
      meaning: "De weg naar links is een doodlopende weg; je kunt hier niet verder doorrijden.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282343-h3-verkeersborden-auto_bb23-spoorwegovergang-over-160-meter.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "92",
      name: "Voorwaarschuwing Doodlopende Weg (L09 variant)",
      description: "Voorwaarschuwing voor een doodlopende weg.",
      meaning: "De weg loopt dood; er is geen uitgang voor doorgaand verkeer.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282458-h3-verkeersborden-auto_bb23-spoorwegovergang-over-240-meter.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "93",
      name: "Aangegeven Rijstrook Heeft Breedte Beperking (L11)",
      description: "Geeft aan dat de aangegeven rijstrook een breedtebeperking heeft.",
      meaning: "Voertuigen die breder zijn dan de aangegeven limiet, mogen deze rijstrook niet gebruiken.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282517-h3-verkeersborden-auto_bw501r-uitwijkroute-rechts-afslaan.png",
      applicableFor: ["vrachtwagen", "bus", "voertuigen met brede lading"],
    },
    {
      _id: "94",
      name: "Vluchthaven (L14)",
      description: "Aanduiding van een vluchthaven.",
      meaning: "Een veilige plek om te stoppen in geval van nood of pech op de snelweg.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282604-h3-verkeersborden-auto_c1-verbodsborden.png",
      applicableFor: ["auto", "motor", "vrachtwagen", "bus"],
    },
    {
      _id: "95",
      name: "Uitwijkplaats Rechts (L20)",
      description: "Aanduiding van een uitwijkplaats aan de rechterzijde.",
      meaning: "Een plek om uit te wijken voor tegemoetkomend verkeer op smalle wegen.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "blauw-wit",
      image: "public/verkeersborden/1739282647-h3-verkeersborden-auto_c2-ob4-verboden-in-te-rijden-inclusief-afgebeelde-voertuigen.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "96",
      name: "Fietsstraat (L51)",
      description: "Geeft het begin van een fietsstraat aan.",
      meaning: "Een straat primair voor fietsers, waar auto's te gast zijn en stapvoets moeten rijden.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739282719-h3-verkeersborden-auto_c2-ob52-verboden-in-te-rijden-met-uitzondering.png",
      applicableFor: ["fiets", "bromfiets", "auto"],
    },
    {
      _id: "97",
      name: "Matrixbord: Einde Aangegeven Verboden/Adviezen",
      description: "Een matrixbord dat het einde van eerder aangegeven verboden of adviezen toont.",
      meaning: "De eerder via matrixborden getoonde beperkingen of adviezen zijn nu opgeheven.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "zwart-wit",
      image: "public/verkeersborden/1739282751-h3-verkeersborden-auto_c3-eenrichtingsweg.png",
      applicableFor: ["auto", "motor", "vrachtwagen", "bus"],
    },
    {
      _id: "98",
      name: "Matrixbord: Verdrijfbord Links",
      description: "Een matrixbord dat aangeeft dat verkeer naar links moet verdrijven.",
      meaning: "Verkeer moet uitwijken naar links, bijvoorbeeld door een obstakel op de rechterrijstrook.",
      category: "gebod",
      type: "gebod" as const,
      shape: "vierkant" as const,
      color: "zwart-wit",
      image: "public/verkeersborden/1739282819-h3-verkeersborden-auto_c04r-eenrichtingsweg-rechts.png",
      applicableFor: ["auto", "motor", "vrachtwagen", "bus"],
    },
    {
      _id: "99",
      name: "Onderbord voor Fietsen (Ob11)",
      description: "Een onderbord dat aangeeft dat het hoofdbord van toepassing is op fietsen.",
      meaning: "De boodschap van het verkeersbord waaronder dit onderbord is geplaatst, geldt specifiek voor fietsers.",
      category: "onderbord",
      type: "onderbord" as const,
      shape: "rechthoek" as const,
      color: "wit-zwart",
      image: "public/verkeersborden/1739282864-h3-verkeersborden-auto_c05-inrijden-toegestaan.png",
      applicableFor: ["fiets"],
    },
    {
      _id: "100",
      name: "Onderbord voor Bussen (Ob12)",
      description: "Een onderbord dat aangeeft dat het hoofdbord van toepassing is op bussen.",
      meaning: "De boodschap van het verkeersbord waaronder dit onderbord is geplaatst, geldt specifiek voor bussen.",
      category: "onderbord",
      type: "onderbord" as const,
      shape: "rechthoek" as const,
      color: "wit-zwart",
      image: "public/verkeersborden/1739282899-h3-verkeersborden-auto_c6-verboden-voor-autos.png",
      applicableFor: ["bus"],
    },
    {
      _id: "101",
      name: "Onderbord voor Vrachtwagens met Tijden (Ob61)",
      description: "Een onderbord dat aangeeft dat het hoofdbord van toepassing is op vrachtwagens gedurende specifieke tijden.",
      meaning: "De boodschap van het verkeersbord waaronder dit onderbord is geplaatst, geldt specifiek voor vrachtwagens binnen de aangegeven tijdsperiode.",
      category: "onderbord",
      type: "onderbord" as const,
      shape: "rechthoek" as const,
      color: "wit-zwart",
      image: "public/verkeersborden/1739282976-h3-verkeersborden-auto_c7-gesloten-voor-vrachtwagens.png",
      applicableFor: ["vrachtwagen"],
    },
    {
      _id: "102",
      name: "Algemeen Voorrangsbord",
      description: "Algemeen voorrangsbord.",
      meaning: "Geeft de geldende voorrangssituatie aan.",
      category: "voorrang",
      type: "voorrang" as const,
      shape: "gevarieerd" as const,
      color: "gevarieerd",
      image: "public/verkeersborden/1739283011-h3-verkeersborden-auto_c9-gesloten-verklaring-tracktor-bromfiets-fiets.png",
      applicableFor: ["alle voertuigen"],
    },
    {
      _id: "103",
      name: "Verkeersbrigadier bij Zebrapad (Vr07)",
      description: "Waarschuwing voor een verkeersbrigadier bij een zebrapad.",
      meaning: "Wees voorbereid op aanwijzingen van een verkeersbrigadier die kinderen helpt oversteken.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739283077-h3-verkeersborden-auto_c11-gesloten-voor-motorfietsen.png",
      applicableFor: ["auto", "bromfiets", "motor", "fiets", "alle voertuigen"],
    },
    {
      _id: "104",
      name: "Algemeen Waarschuwingsbord",
      description: "Een algemeen waarschuwingsbord voor een niet-gespecificeerd gevaar.",
      meaning: "Wees extra voorzichtig; er is een onbekend gevaar of situatie die aandacht vereist.",
      category: "waarschuwing",
      type: "waarschuwing" as const,
      shape: "driehoek" as const,
      color: "rood-wit",
      image: "public/verkeersborden/1739283178-h3-verkeersborden-auto_c12-verboden-voor-autos-en-motoren.png",
      applicableFor: ["auto", "bromfiets", "motor", "alle voertuigen"],
    },
    {
      _id: "105",
      name: "Omleidingsroute Volgen Rechtsaf (WIU T201)",
      description: "Geeft aan dat je een omleidingsroute moet volgen door rechtsaf te slaan.",
      meaning: "Volg de omleiding door hier rechtsaf te slaan.",
      category: "informatie",
      type: "informatie" as const,
      shape: "vierkant" as const,
      color: "oranje-zwart",
      image: "public/verkeersborden/1739283238-h3-verkeersborden-auto_c16-verboden-voor-voetgangers.png",
      applicableFor: ["auto", "motor", "vrachtwagen", "bus"],
    },
  ];

  // Filter by category (vehicle type)
   let filteredSigns = allSigns.filter((sign) => {
    if (category === "auto") {
      return sign.applicableFor.includes("auto") || sign.applicableFor.includes("alle voertuigen")
    } else if (category === "bromfiets") {
      return sign.applicableFor.includes("bromfiets") || sign.applicableFor.includes("alle voertuigen")
    } else if (category === "motor") {
      return sign.applicableFor.includes("motor") || sign.applicableFor.includes("alle voertuigen")
    }
    return true
  })

  // Filter by type if specified
  if (type && type !== "all") {
    filteredSigns = filteredSigns.filter((sign) => sign.type === type)
  }

  return filteredSigns.slice(0, limit)
}